language: cpp

services:
  - docker

compiler:
  - gcc

before_install:
  - docker pull roman3349/fit-bit-ivs-2019-project:ubuntu-bionic
  - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/ivs -td roman3349/fit-bit-ivs-2019-project:ubuntu-bionic /bin/bash

script:
  - docker exec -ti travis-ci bash -c "cd /ivs && make all"
  - docker exec -ti travis-ci bash -c "cd /ivs && make test"

after_script:
  - docker stop travis-ci
