dist: xenial

language: cpp

addons:
  apt:
    sources:
      - ppa:isc/bind
    packages:
      - libgtkmm-3.0-dev
      - libgtest-dev
      - googletest

compiler:
  - clang
  - gcc

script:
  - make all
  - make test